# Configurações para Streamlit Cloud
# Copie este conteúdo para o campo "Secrets" no Streamlit Cloud

# Configurações básicas
APP_NAME = "Jurisprudência TJSP"
DEBUG = false

# Configurações de segurança
SECRET_KEY = "sua-chave-secreta-aqui-mude-isso"

# Configurações do TJSP (importante para funcionar)
TJSP_BASE_URL = "https://esaj.tjsp.jus.br"
TJSP_TIMEOUT = 30
TJSP_MAX_RETRIES = 3

# Rate limiting (importante para não ser bloqueado)
REQUEST_DELAY_MIN = 3
REQUEST_DELAY_MAX = 7
MAX_REQUESTS_PER_MINUTE = 10

# Cache
CACHE_TTL = 3600  # 1 hora

# Opcional: APIs de IA (se quiser usar no futuro)
# OPENAI_API_KEY = "sua-chave-aqui"
# GROQ_API_KEY = "sua-chave-aqui"