apiVersion: v1
kind: ConfigMap
metadata:
  name: jurisprudencia-config
  namespace: jurisprudencia
data:
  # Database
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "jurisprudencia_db"
  DB_USER: "jurisprudencia"
  
  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # API
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  
  # Model
  EMBEDDING_MODEL: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  
  # Paths
  PDF_STORAGE_PATH: "/app/data/pdfs"
  LOG_PATH: "/app/logs"
  
  # Environment
  ENVIRONMENT: "production"
  PYTHONPATH: "/app"